/*
 * Sistema para Tienda de Ropas Realizado en Java.
*Este sistema te permite realizar un control de las ventas realizadas,
*facilitando a tras ves de los campos poder elejir si la prenda es de industria Nacional o Extranjera, ademas nos 
*da la opcion de  seleccionar Talle (S,M,L).
*El sistema nos pide Prenda , Cantidad y Precio para luego realizar un calculo segun los descuentos vigentes,  a su ves
*nos permite saber el total de la prenda ingresada para luego verse reflejada en la tabla de detalles.
 */
package com.mycompany.sistematiendaropa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolas
 */
//CONEXION CON JFRAME
public class frmSistemaTiendaRopa extends javax.swing.JFrame {

    /**
     * Creates new form frmSistemaTiendaRopa
     */
    //ESTE METODO NOS PERMITE ESTABLECER LOS MODELOS
    public frmSistemaTiendaRopa() {
        initComponents();
        this.tabaldetalles.setModel(modelo);
        this.modelo.addColumn("NACIONALIDAD");
        this.modelo.addColumn("GENERO");
        this.modelo.addColumn("TALLAS");
        this.modelo.addColumn("PRENDAS");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("PRECIO UNITARIO");
        this.modelo.addColumn("TOTAL A PAGAR");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultTableModel modelo = new DefaultTableModel();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbonacionalidad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        botonh = new javax.swing.JRadioButton();
        botonm = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        cbotallas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtprenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btngenerar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabaldetalles = new javax.swing.JTable();
        btnlimpiartabla = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        btnnetopagar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtnetopagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA DE COMPRAS DE ROPA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descuentos/Promos"));

        jLabel2.setText("Nacional");

        jLabel3.setText("HOMBRE TALLA: S=0.05,M=0.07,L=0.10");

        jLabel4.setText("MUJER TALLA: S=0.04,M=0.09,L=0.12");

        jLabel5.setText("Internacionales");

        jLabel6.setText("HOMBRE TALLA: S=0.04,M=0.09,L=0.12");

        jLabel7.setText("MUJER TALLA: S=0.05,M=0.07,L=0.10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar Compra"));

        jLabel8.setText("Nacionalidad");

        cbonacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Argentino", "Extranjero" }));
        cbonacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbonacionalidadActionPerformed(evt);
            }
        });

        jLabel10.setText("Genero");

        buttonGroup1.add(botonh);
        botonh.setText("Hombre");
        botonh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonhActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonm);
        botonm.setText("Mujer");
        botonm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmActionPerformed(evt);
            }
        });

        jLabel11.setText("Talle");

        cbotallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "S", "M", "L" }));

        jLabel9.setText("Prenda:");

        jLabel12.setText("Cantidad");

        jLabel13.setText("Precio:");

        jLabel14.setText("TOTAL:");

        btngenerar.setText("Generar Compra");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jLabel14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel11)
                                .addGap(36, 36, 36))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonm)
                                .addGap(18, 18, 18)
                                .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btngenerar)
                                .addGap(58, 58, 58)
                                .addComponent(btnlimpiar)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel13)))
                        .addGap(53, 53, 53))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonh)
                                .addComponent(botonm)
                                .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(29, 29, 29)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngenerar)
                    .addComponent(btnlimpiar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tabaldetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabaldetalles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        btnlimpiartabla.setText("Limpiat Tabla");
        btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablaActionPerformed(evt);
            }
        });

        btnquitar.setText("Quitar Compra");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        btnnetopagar.setText("Neto a Pagar");

        jLabel15.setText("Neto a Pagas S/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnlimpiartabla)
                                .addGap(50, 50, 50)
                                .addComponent(btnquitar)
                                .addGap(41, 41, 41)
                                .addComponent(btnnetopagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiartabla)
                    .addComponent(btnquitar)
                    .addComponent(btnnetopagar)
                    .addComponent(jLabel15)
                    .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbonacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbonacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbonacionalidadActionPerformed

    private void botonhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonhActionPerformed

    private void botonmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonmActionPerformed
//BOTON QUE NOS PERMITE LIMPIAR LOS DATOS INGRESADOS EN EL FORMULARIO
    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        this.cbonacionalidad.setSelectedIndex(0);
        if (botonh.isSelected()) {

        }
        if (botonm.isSelected()) {

        }
        this.cbotallas.setSelectedIndex(0);
        this.txtprenda.setText("");
        this.txtcantidad.setText("");
        this.txtprecio.setText("");
        this.txttotal.setText("");


    }//GEN-LAST:event_btnlimpiarActionPerformed
// BOTON QUE NOS PERMITE GENERAR LA COMPRA PARA LUEGO APARACER EN LA TABLA DE REGISTRO DE DETALLES
    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        // TODO add your handling code here:
        descuentos_hombres_argentinos();
        descuentos_mujeres_argentinas();
        descuentos_hombres_internacionales();
        descuentos_mujeres_internacionales();
        //LLAVE ABREN Y CIERRAN
        if (botonh.isSelected()) {
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedItem(), "Hombre",
                this.cbotallas.getSelectedItem(), this.txtprenda.getText(), this.txtcantidad.getText(),
                this.txtprecio.getText(), this.txttotal.getText()});
        } else if (botonm.isSelected()) {
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedItem(), "Mujer",
                this.cbotallas.getSelectedItem(), this.txtprenda.getText(), this.txtcantidad.getText(),
                this.txtprecio.getText(), this.txttotal.getText()});
        }

    }//GEN-LAST:event_btngenerarActionPerformed
//BOTON QUE NOS PERMITE QUITAR ELEMENTOS DE LA TABLA DE DETALLES
    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        // TODO add your handling code here:
        modelo.removeRow(this.tabaldetalles.getSelectedRow());
    }//GEN-LAST:event_btnquitarActionPerformed
//BOTON QUE NOS PERMITE VACIAR LA TABLA DE DETALLES COMPLETA 
    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        // TODO add your handling code here:
        int x = this.modelo.getRowCount();
        for (int y = 0; y < x; y++) {
            this.modelo.removeRow(0);
        }
        this.txtnetopagar.setText("");
    }//GEN-LAST:event_btnlimpiartablaActionPerformed

    //DESCUENTOS APLICADOS A LOS HOMBRES INTERNACIONALES
    public void descuentos_hombres_internacionales() {
        double cantidad_s, precio_s, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.09;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        //SELECCION DE TALLE S
        if (cbonacionalidad.getSelectedIndex() == 2) {
            if (this.botonh.isSelected()) {
                if (cbotallas.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SELECCION TALLE M
        if (cbonacionalidad.getSelectedIndex() == 2) {
            if (this.botonh.isSelected()) {
                if (cbotallas.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SELECCION TALLE L
        if (cbonacionalidad.getSelectedIndex() == 2) {
            if (this.botonh.isSelected()) {
                if (cbotallas.getSelectedIndex() == 3) {
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }

    }
    //DESCUENTOS APLICADOS A LOS MUJERES INTERNACIONALES

    public void descuentos_mujeres_internacionales() {
        double cantidad_s, precio_s, total_s, desc_s = 0.05;
        double cantidad_m, precio_m, total_m, desc_m = 0.07;
        double cantidad_l, precio_l, total_l, desc_l = 0.10;
        //SELECCION TALLE  S
        if (cbonacionalidad.getSelectedIndex() == 2) {
            if (this.botonm.isSelected()) {
                if (cbotallas.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }

            }
        }
        //SELECCION TALLE M
        if (cbonacionalidad.getSelectedIndex() == 2) {
            if (this.botonm.isSelected()) {
                if (cbotallas.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }

            }
        }
        //SELECCION TALLE  L
        if (cbonacionalidad.getSelectedIndex() == 2) {
            if (this.botonm.isSelected()) {
                if (cbotallas.getSelectedIndex() == 3) {
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }

            }
        }

    }
    //DESCUENTOS APLICADOS A LOS MUJERES NACIONALES

    public void descuentos_mujeres_argentinas() {
        double cantidad_s, precio_s, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.04;
        double cantidad_l, precio_l, total_l, desc_l = 0.04;
        //SELECCIONA TALLE S
        if (cbonacionalidad.getSelectedIndex() == 1) {
            if (this.botonm.isSelected()) {
                if (cbotallas.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SELECCION TALLE M
        if (cbonacionalidad.getSelectedIndex() == 1) {
            if (this.botonm.isSelected()) {
                if (cbotallas.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SELECCION TALLE L
        if (cbonacionalidad.getSelectedIndex() == 1) {
            if (this.botonm.isSelected()) {
                if (cbotallas.getSelectedIndex() == 3) {
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }
    }
    //DESCUENTOS APLICADOS A LOS HOMBRES NACIONALES

    public void descuentos_hombres_argentinos() {
        double cantidad_s, precio_s, total_s, desc_s = 0.05;
        double cantidad_m, precio_m, total_m, desc_m = 0.07;
        double cantidad_l, precio_l, total_l, desc_l = 0.10;

        //SELECCION TALLE S 
        if (cbonacionalidad.getSelectedIndex() == 1) {
            if (this.botonh.isSelected()) {
                if (cbotallas.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SELECCION TALLE M
        if (cbonacionalidad.getSelectedIndex() == 1) {
            if (this.botonh.isSelected()) {
                if (cbotallas.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SELECCION TALLE L
        if (cbonacionalidad.getSelectedIndex() == 1) {
            if (this.botonh.isSelected()) {
                if (cbotallas.getSelectedIndex() == 2) {
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTiendaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSistemaTiendaRopa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonh;
    private javax.swing.JRadioButton botonm;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JButton btnnetopagar;
    private javax.swing.JButton btnquitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbonacionalidad;
    private javax.swing.JComboBox<String> cbotallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabaldetalles;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnetopagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprenda;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
